### ISSUE TITLE
Tailwind v1+ support

### ISSUE THREAD

**Issue by benjivm** [magicspon/tailwind-not-last-child#1]
This plugin no longer seems to be working on the latest version of [Tailwind](https://tailwindcss.com/docs/plugins/#app), can you update it?

**Comment by magicspon** [comment]
I'd suggest using the new custom variants feature

https://tailwindcss.com/docs/plugins#adding-variants

```javascript
module.exports = {
  plugins: [
    function({ addVariant, e }) {
      addVariant('not-last', ({ modifySelectors, separator }) => {
        modifySelectors(({ className }) => {
          return `.${e(`${separator}${className}:not(:last-child)`)}`
        })
      })
    }
  ]
}
```

**Comment by benjivm** [comment]
Thanks for the response; I can't seem to get that or any of the Variants examples from the documentation working, though the other ones do (`addComponent`, `addUtilities`, etc.). Does the code you posted and the `first-child` example from the docs work for you? I'm on Tailwind v1.0.3.

**Comment by magicspon** [comment]
Have you added 'not-last' (or any other variant) to the variant list

```javascript
module.exports = {
  variants: {
    appearance: ['responsive'],
    // ...
    borderColor: ['responsive', 'hover', 'focus', 'not-last'],
    // ...
    outline: ['responsive', 'focus'],
    // ...
    zIndex: ['responsive'],
  },
}
```

**Comment by benjivm** [comment]
Thank you, that was one of the issues. I also needed to modify the function:

```
function({ addVariant, e }) {
    addVariant('not-last', ({ modifySelectors, separator }) => {
        modifySelectors(({ className }) => {
            return `.${e(`not-last${separator}${className}`)}:not(:last-child)`;
        });
    });
},
```

**Comment by magicspon** [comment]
what is the change....

FYI.... if you write 'javascript' after '```' it will add syntax highlighting
